---
title: "flux"
author: "Maxwel Coura Oliveira"
date: "11/7/2019"
output: html_document
---

```{r include=FALSE}
library(tidyverse)
```

```{r}
data <- read.csv("flux.csv") %>% 
  mutate(yy = y/1000)
glimpse(data)
#View(data)
```


```{r}
data$Type <- factor(data$Type, levels = c("aerodnamic", "integrated"), labels=c("Aerodynamic Method", "Integrated Horizontal Flux Method"))
```




```{r}
ggplot(data, aes(x=Time, y=y, color=Location)) + geom_point() + geom_line() + 
  facet_grid(~Type) + theme_bw() + 
  labs(x="Hours after application", y=bquote('Dicamba flux ('*eta~'g'~m^-2~s^-1*')')) +
  theme(legend.position=c(0.435, 0.83), panel.grid = element_blank(), legend.text = element_text(size=12), axis.title = element_text(size=15, color = "black"), legend.title = element_blank(), axis.text = element_text(size=14, color = "black"), strip.text = element_text(size=14)) + scale_color_manual(values=c("orange", "black", "darkgreen",  "darkviolet", "blue", "red")) +
  ggsave("Flux.tiff", height = 6, width = 12, dpi=300)
```

